### PR TITLE
fix(poster): avoid conflict with click_to_pause plugin

### LINKED ISSUE #1829: bug(poster-plugin): click event conflicts with click_to_pause if audio only
**Browser**: any

**OS**: any

**Clappr Version**: latest

**Steps to reproduce**:

* load an audio only source, for example,  `https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_5MG.mp3`

Video will start when clicking on poster, but then since poster is [still displayed with audio](https://github.com/clappr/clappr/blob/dev/src/plugins/poster/poster.js#L108), the click event will not be propagated to `click_to_pause` plugin. _(with video source, the poster css display value is none)_.

### PR DESCRIPTION
**Pull request by kslimani**
Should fix #1829 issue.

### CODE REVIEW

**Comment by kslimani** [comment]
Travis seems to have failed because `/etc/init.d/xvfb` may be missing.

File: src/plugins/poster/poster.js [hunk 1]
```diff
@@ -95,12 +95,15 @@ export default class PosterPlugin extends UIContainerPlugin {
   }
 
   clicked() {
-    if (!this.options.chromeless || this.options.allowUserInteraction) {
-      this.playRequested = true
-      this.update()
-      this.container.play()
+    // Let "click_to_pause" plugin handle click event if media has started playing
+    if (! this.hasStartedPlaying) {
```
Comment (leandromoreira) [inline src/plugins/poster/poster.js]: can't we inline this condition?
```js
if (! this.hasStartedPlaying && (!this.options.chromeless || this.options.allowUserInteraction)) {}
```

File: src/plugins/poster/poster.js [hunk 2]
```diff
@@ -95,12 +95,15 @@ export default class PosterPlugin extends UIContainerPlugin {
...
+      if (!this.options.chromeless || this.options.allowUserInteraction) {
+        this.playRequested = true
+        this.update()
+        this.container.play()
+      }
+      return false
     }
```
Comment (leandromoreira) [inline src/plugins/poster/poster.js]: Shouldn't we always return something? I think the last `return` is missing

Comment (kslimani) [reply src/plugins/poster/poster.js]: @leandromoreira if you return false, then click event is not propagated  (and therefore click_to_pause plugin click is not triggered).

File: src/plugins/poster/poster.js (hunk 1 above)
Comment (kslimani) [reply src/plugins/poster/poster.js]: The condition could be rewrited, maybe removing the return false because of hasStartedPlaying check. I writed it this way to ensure it do not break anything.

Comment (kslimani) [reply src/plugins/poster/poster.js]: Also if you rewrite the condition that way, with audio only, if you seek almost to end, then wai for video to stop and display poster play icon, then if you click, it does not start the video.

Comment (kslimani) [reply src/plugins/poster/poster.js]: @leandromoreira  In fact, the return false is required when click is handled by poster. Returning false disrupt the click event and container click if not triggered. Otherwise, if triggered the media is immediatly paused by `click_to_pause` plugin.

Just experiment the branch by yourself :)

**Comment by towerz** [comment]
@kslimani our travis config has been updated to fix an issue with PR checks. Could you update your branch with the latest `dev`?
